name: Docker Multi-Arch Build

on:
  push:
    tags: ["v*"]
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            aidedaijiayang/quiz-cat:${{ github.ref_name }}
            aidedaijiayang/quiz-cat:latest
          labels: |
            org.opencontainers.image.description="Quiz Cat - 智能学习平台"
            org.opencontainers.image.source="https://github.com/migumigu/quiz-cat"
          build-args: |
            README_FILE=dockerhub-README.md

      - name: Update Docker Hub Description
        if: success()
        run: |
          echo "Updating Docker Hub description..."
          TOKEN=$(curl -s -H "Content-Type: application/json" \
            -X POST -d '{"username":"${{ secrets.DOCKER_HUB_USERNAME }}","password":"${{ secrets.DOCKER_HUB_TOKEN }}"}' \
            https://hub.docker.com/v2/users/login/ | jq -r .token)
          
          DESCRIPTION=$(cat dockerhub-README.md | jq -sR .)
          curl -X PATCH \
            -H "Authorization: JWT $TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"full_description": '"$DESCRIPTION"'}' \
            https://hub.docker.com/v2/repositories/aidedaijiayang/quiz-cat/
          cache-from: type=gha
          cache-to: type=gha,mode=max